/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCallbackRouteImport } from './routes/api/callback'
import { Route as ApiAuthRouteImport } from './routes/api/auth'

const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallbackRoute = ApiCallbackRouteImport.update({
  id: '/api/callback',
  path: '/api/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/partenaires': typeof PartenairesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/callback': typeof ApiCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/partenaires': typeof PartenairesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/callback': typeof ApiCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/partenaires': typeof PartenairesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/callback': typeof ApiCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/partenaires' | '/api/auth' | '/api/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/partenaires' | '/api/auth' | '/api/callback'
  id: '__root__' | '/' | '/partenaires' | '/api/auth' | '/api/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PartenairesRoute: typeof PartenairesRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiCallbackRoute: typeof ApiCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/callback': {
      id: '/api/callback'
      path: '/api/callback'
      fullPath: '/api/callback'
      preLoaderRoute: typeof ApiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PartenairesRoute: PartenairesRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiCallbackRoute: ApiCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
